definitions:
  web.errorResponse:
    properties:
      code:
        type: string
      message:
        type: string
      status:
        type: integer
    type: object
  web.response:
    properties:
      data: {}
    type: object
info:
  contact:
    name: Antonini y Dagoberto
    url: https://www.linkedin.com/in/carlaantonini/ https://www.linkedin.com/in/gustavo-dagoberto/
  description: Esta api maneja un servicio de turnos para una clinica odontológica,
    manejando los datos de pacientes y odontologos
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Grupo Antonini-Dago Certified Tech Developer
  version: "1.0"
paths:
  /odontologos/:id:
    delete:
      consumes:
      - application/json
      description: Elimina un odontólogo por su id si se tiene los permisos de usuario
        adecuados
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: DeletById odontologo
      tags:
      - domains.odontologoDomain
  /turnos:
    post:
      consumes:
      - application/json
      description: Create nuevo turno con el DNI del paciente y la Matricula del odontólogo
        si se tiene los permisos de usuario adecuados
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Crea un turno con dni y matricula
      tags:
      - domains.turnoDomain
  /turnos/:id:
    delete:
      consumes:
      - application/json
      description: Elimina turno por su ID si se tiene los permisos de usuario adecuados
      parameters:
      - description: id del turno
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Delete turno
      tags:
      - domains.turnoDomain
swagger: "2.0"
